# Generated by Django 4.0.2 on 2022-02-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
    ]
