# Generated by Django 4.0.2 on 2022-04-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
