# Generated by Django 4.0.2 on 2022-04-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
        migrations.DeleteModel(
            name='staff',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
