# Generated by Django 4.0.2 on 2022-04-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_staff_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='username',
        ),
    ]
