# Generated by Django 4.0.2 on 2022-04-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_staff_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('section', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
            ],
        ),
    ]
