# Generated by Django 4.0.2 on 2022-04-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='items',
            field=models.ImageField(blank=True, null=True, upload_to='propic/items'),
        ),
        migrations.AddField(
            model_name='staff',
            name='item',
            field=models.ImageField(blank=True, null=True, upload_to='propic/items'),
        ),
    ]
