# Generated by Django 4.0.2 on 2022-04-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_doctor_items_staff_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('age', models.IntegerField()),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.doctor')),
            ],
        ),
    ]
