# Generated by Django 4.0.2 on 2022-04-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='section',
        ),
    ]
