# Generated by Django 4.0.2 on 2022-04-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_patient_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='section',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
