# Generated by Django 4.0.2 on 2022-04-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_doctor_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='patient',
            new_name='pat',
        ),
    ]
