# Generated by Django 4.0.2 on 2022-04-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_rename_patient_doctor_pat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='pat',
            new_name='patient',
        ),
    ]
