# Generated by Django 4.0.2 on 2022-04-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_remove_doctor_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section_name', models.CharField(max_length=225)),
                ('room_no', models.IntegerField()),
            ],
        ),
    ]
