# Generated by Django 4.0.2 on 2022-04-07 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.section'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.section'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.section'),
        ),
    ]
